// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("UniProtProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("UniProtProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing UniProtProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "UniProtProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "UniProtProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing UniProtProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
